config/routes.rb
Rails.application.routes.draw do
  get "posts/index"

  devise_for :users
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  resources :posts

  root 'posts#index'
  get "posts/most_viewed" => "posts#most_viewed"

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         

   #Association
   has_many :posts      
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_filter :authenticate_user!
	def index
		@posts=Post.all
		@list=Post.order("view_count DESC").limit(3)
	end
	def new
		@post=Post.new
	end
	def create
		@post = Post.new(post_params)
		respond_to do |format|
			if @post.save
				format.html { redirect_to @post, notice: 'Post was successfully created.' }
				format.json { render action: 'show', status: :created, location: @post }
			else
				format.html { render action: 'new' }
				format.json { render json: @post.errors, status: :unprocessable_entity }
			end
		end
	end
	def show
		@post = Post.find(params[:id])
		@post.increment(:view_count)
		@post.save
	end
	def most_viewed
		
	end
	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		respond_to do |format|
			format.html { redirect_to posts_url }
			format.json { head :no_contentpost  }
		end
	end

	def post_params
		params.require(:post).permit(:post,:user_id)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_slider.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner slide">
  <% i=0 %>
    <% @list.each do |l| %>
      <% if i==0 %>
    <div class="item active slider slide-content">
    <% else %>
    <div class="item slider slide-content">
    <% end %>
      <%= l.post %>
      <% i=i+1 %>
      <div class="carousel-caption">

      </div>
    </div>
    <% end %>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>PostApp</title>
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
</head>
<body>


	<div class="container">
		<div id="user_nav">
			<% if user_signed_in? %>
			Signed in as <%= current_user.email %>
			<%= link_to "Sign out", destroy_user_session_path, :method => 'delete' %>
			<% else %>
			<%= link_to "Sign up", new_user_registration_path %> or <%= link_to "Sign_in", new_user_session_path %>
			<% end %>
		</div>
		<div class="all">
	<%= yield %>
	</div>
</div>
</body>
</html>

app/views/posts/index.html.erb
<div class="row">
	<div class="col-xs-12">
	<%= render partial: "layouts/slider" %>
	</div>
</div>
<div class="row">
	<div class="col-xs-1"></div>
	<div class="col-xs-11 title">POSTS</div>
</div>
<div class="row">
	<% @posts.each do |p| %>

	<div class="col-xs-8"><%= p.post %></div>

	<div class="col-xs-2"><%= link_to 'Show', p %></div>
	<div class="col-xs-2">
		<% if (p.user_id==current_user.id) %>
		<%= link_to 'Destroy', p, method: :delete, data: { confirm: 'Are you sure?' } %>
		<% end %>
	</div>

	<% end %>
</div>
<div class="row">
	<div class="col-xs-10"></div>
	<div class="col-xs-2 new-post">
		<%= link_to 'Add New Post', new_post_path %>
	</div>
</div>

app/views/posts/most_viewed.html.erb
<% @post.each do |p| %>
<%= p.id %>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= form_for @post, :url => { :action => "create" }  do |f|  %>
	<%= f.hidden_field :user_id, :value =>current_user.id%>
    <%= f.text_field  :post %>

    <%= f.submit "Add post", class: "btn btn-primary" %>
 <%end%>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
 <p><id="notice"><%= notice %></p>
 <div class="row">
 	<div class="col-xs-1"></div>
 	<div class="col-xs-11">
 		<strong class="title">Post:</strong>
 	</div>
 </div>
 <div class="row">
 	<div class="col-xs-1"></div>
 	<div class="col-xs-8"><%= @post.post %></div>
 	<div class="col-xs-3"></div>
 </div>


 <%= link_to 'Back', posts_path %>